export const NEW_ORDER_SUCCESS="NEW_ORDER_SUCCESS";
export const NEW_ORDER_FAIL="NEW_ORDER_FAIL";
export const NEW_ORDER_REQUEST="NEW_ORDER_REQUEST";

export const MY_ORDER_SUCCESS="MY_ORDER_SUCCESS";
export const MY_ORDER_FAIL="MY_ORDER_FAIL";
export const MY_ORDER_REQUEST="MY_ORDER_REQUEST";

export const SINGLE_ORDER_SUCCESS="SINGLE_ORDER_SUCCESS";
export const SINGLE_ORDER_FAIL="SINGLE_ORDER_FAIL";
export const SINGLE_ORDER_REQUEST="SINGLE_ORDER_REQUEST";

export const ALL_ERROR_CLEAR="ALL_ERROR_CLEA";