export const NEW_ORDER_SUCCESS="NEW_ORDER_SUCCESS";
export const NEW_ORDER_FAIL="NEW_ORDER_FAIL";
export const NEW_ORDER_REQUEST="NEW_ORDER_REQUEST";

export const MY_ORDER_SUCCESS="MY_ORDER_SUCCESS";
export const MY_ORDER_FAIL="MY_ORDER_FAIL";
export const MY_ORDER_REQUEST="MY_ORDER_REQUEST";

export const SINGLE_ORDER_SUCCESS="SINGLE_ORDER_SUCCESS";
export const SINGLE_ORDER_FAIL="SINGLE_ORDER_FAIL";
export const SINGLE_ORDER_REQUEST="SINGLE_ORDER_REQUEST";

export const ADMIN_ORDER_SUCCESS="ADMIN_ORDER_SUCCESS";
export const ADMIN_ORDER_FAIL="ADMIN_ORDER_FAIL";
export const ADMIN_ORDER_REQUEST="ADMIN_ORDER_REQUEST";

export const ADMIN_ORDER_CREATE_SUCCESS="ADMIN_ORDER_CREATE_SUCCESS";
export const ADMIN_ORDER_CREATE_FAIL="ADMIN_ORDER_CREATE_FAIL";
export const ADMIN_ORDER_CREATE_REQUEST="ADMIN_ORDER_CREATE_REQUEST";
export const ADMIN_ORDER_CREATE_RESET="ADMIN_ORDER_CREATE_RESET";

export const ADMIN_ORDER_DELETE_SUCCESS="ADMIN_ORDER_DELETE_SUCCESS";
export const ADMIN_ORDER_DELETE_FAIL="ADMIN_ORDER_DELETE_FAIL";
export const ADMIN_ORDER_DELETE_REQUEST="ADMIN_ORDER_DELETE_REQUEST";
export const ADMIN_ORDER_DELETE_RESET="ADMIN_ORDER_DELETE_RESET";

export const ADMIN_ORDER_UPDATE_SUCCESS="ADMIN_ORDER_UPDATE_SUCCESS";
export const ADMIN_ORDER_UPDATE_FAIL="ADMIN_ORDER_UPDATE_FAIL";
export const ADMIN_ORDER_UPDATE_REQUEST="ADMIN_ORDER_UPDATE_REQUEST";
export const ADMIN_ORDER_UPDATE_RESET="ADMIN_ORDER_UPDATE_RESET";


export const ALL_ERROR_CLEAR="ALL_ERROR_CLEA";