export const ALL_PRODUCT_SUCCESS="ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL="ALL_PRODUCT_FAIL";
export const ALL_PRODUCT_REQUEST="ALL_PRODUCT_REQUEST";

export const ONE_PRODUCT_SUCCESS="ONE_PRODUCT_SUCCESS";
export const ONE_PRODUCT_FAIL="ONE_PRODUCT_FAIL";
export const ONE_PRODUCT_REQUEST="ONE_PRODUCT_REQUEST";

export const REVIEW_SUCCESS="REVIEW_SUCCESS";
export const REVIEW_PRODUCT_FAIL="REVIEW_FAIL";
export const REVIEW_PRODUCT_REQUEST="REVIEW_REQUEST";
export const REVIEW_PRODUCT_RESET="REVIEW_RESET";

export const ADMIN_PRODUCT_SUCCESS="ADMIN_PRODUCT_SUCCESS";
export const ADMIN_PRODUCT_FAIL="ADMIN_PRODUCT_FAIL";
export const ADMIN_PRODUCT_REQUEST="ADMIN_PRODUCT_REQUEST";

export const ADMIN_PRODUCT_CREATE_SUCCESS="ADMIN_PRODUCT_CREATE_SUCCESS";
export const ADMIN_PRODUCT_CREATE_FAIL="ADMIN_PRODUCT_CREATE_FAIL";
export const ADMIN_PRODUCT_CREATE_REQUEST="ADMIN_PRODUCT_CREATE_REQUEST";
export const ADMIN_PRODUCT_CREATE_RESET="ADMIN_PRODUCT_CREATE_RESET";

export const ADMIN_PRODUCT_DELETE_SUCCESS="ADMIN_PRODUCT_DELETE_SUCCESS";
export const ADMIN_PRODUCT_DELETE_FAIL="ADMIN_PRODUCT_DELETE_FAIL";
export const ADMIN_PRODUCT_DELETE_REQUEST="ADMIN_PRODUCT_DELETE_REQUEST";
export const ADMIN_PRODUCT_DELETE_RESET="ADMIN_PRODUCT_DELETE_RESET";

export const ADMIN_PRODUCT_UPDATE_SUCCESS="ADMIN_PRODUCT_UPDATE_SUCCESS";
export const ADMIN_PRODUCT_UPDATE_FAIL="ADMIN_PRODUCT_UPDATE_FAIL";
export const ADMIN_PRODUCT_UPDATE_REQUEST="ADMIN_PRODUCT_UPDATE_REQUEST";
export const ADMIN_PRODUCT_UPDATE_RESET="ADMIN_PRODUCT_UPDATE_RESET";

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const ALL_ERROR_CLEAR="ALL_ERROR_CLEA";