export const ALL_PRODUCT_SUCCESS="ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL="ALL_PRODUCT_FAIL";
export const ALL_PRODUCT_REQUEST="ALL_PRODUCT_REQUEST";

export const ONE_PRODUCT_SUCCESS="ONE_PRODUCT_SUCCESS";
export const ONE_PRODUCT_FAIL="ONE_PRODUCT_FAIL";
export const ONE_PRODUCT_REQUEST="ONE_PRODUCT_REQUEST";

export const REVIEW_SUCCESS="REVIEW_SUCCESS";
export const REVIEW_PRODUCT_FAIL="REVIEW_FAIL";
export const REVIEW_PRODUCT_REQUEST="REVIEW_REQUEST";
export const REVIEW_PRODUCT_RESET="REVIEW_RESET";

export const ADMIN_PRODUCT_SUCCESS="ADMIN_PRODUCT_SUCCESS";
export const ADMIN_PRODUCT_FAIL="ADMIN_PRODUCT_FAIL";
export const ADMIN_PRODUCT_REQUEST="ADMIN_PRODUCT_REQUEST";

export const ADMIN_PRODUCT_CREATE_SUCCESS="ADMIN_PRODUCT_CREATE_SUCCESS";
export const ADMIN_PRODUCT_CREATE_FAIL="ADMIN_PRODUCT_CREATE_FAIL";
export const ADMIN_PRODUCT_CREATE_REQUEST="ADMIN_PRODUCT_CREATE_REQUEST";
export const ADMIN_PRODUCT_CREATE_RESET="ADMIN_PRODUCT_CREATE_RESET";



export const ALL_ERROR_CLEAR="ALL_ERROR_CLEA";