export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAIL="LOGIN_FAIL";
export const LOGIN_REQUEST="LOGIN_REQUEST";

export const REGISTER_SUCCESS="REGISTER_SUCCESS";
export const REGISTER_FAIL="REGISTER_FAIL";
export const REGISTER_REQUEST="REGISTER_REQUEST";

export const ME_USER_SUCCESS="ME_USER_SUCCESS";
export const ME_USER_FAIL="ME_USER_FAIL";
export const ME_USER_REQUEST="ME_USER_REQUEST";

export const ME_USER_LOGOUT_SUCCESS="ME_USER_LOGOUT_SUCCESS";
export const ME_USER_LOGOUT_FAIL="ME_USER_LOGOUT_FAIL";

export const ALL_ERROR_CLEAR="ALL_ERROR_CLEA";