export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAIL="LOGIN_FAIL";
export const LOGIN_REQUEST="LOGIN_REQUEST";

export const REGISTER_SUCCESS="REGISTER_SUCCESS";
export const REGISTER_FAIL="REGISTER_FAIL";
export const REGISTER_REQUEST="REGISTER_REQUEST";

export const ME_USER_SUCCESS="ME_USER_SUCCESS";
export const ME_USER_FAIL="ME_USER_FAIL";
export const ME_USER_REQUEST="ME_USER_REQUEST";

export const ME_USER_LOGOUT_SUCCESS="ME_USER_LOGOUT_SUCCESS";
export const ME_USER_LOGOUT_FAIL="ME_USER_LOGOUT_FAIL";

export const ME_USER_UPDATE_SUCCESS="ME_USER_UPDATE_SUCCESS";
export const ME_USER_UPDATE_FAIL="ME_USER_UPDATE_FAIL";
export const ME_USER_UPDATE_RESET="ME_USER_UPDATE_RESET";
export const ME_USER_UPDATE_REQUEST="ME_USER_UPDATE_REQUEST";

export const ME_USER_UPDATE_PASSWORD_SUCCESS="ME_USER_UPDATE_PASSWORD_SUCCESS";
export const ME_USER_UPDATE_PASSWORD_FAIL="ME_USER_UPDATE_PASSWORD_FAIL";
export const ME_USER_UPDATE_PASSWORD_RESET="ME_USER_UPDATE_PASSWORD_RESET";
export const ME_USER_UPDATE_PASSWORD_REQUEST="ME_USER_UPDATE_PASSWORD_REQUEST";

export const ME_USER_RESET_PASSWORD_SUCCESS="ME_USER_RESET_PASSWORD_SUCCESS";
export const ME_USER_RESET_PASSWORD_FAIL="ME_USER_RESET_PASSWORD_FAIL";
export const ME_USER_RESET_PASSWORD_REQUEST="ME_USER_RESET_PASSWORD_REQUEST";

export const ME_USER_RESET_TOKEN_PASSWORD_SUCCESS="ME_USER_RESET_TOKEN_PASSWORD_SUCCESS";
export const ME_USER_RESET_TOKEN_PASSWORD_FAIL="ME_USER_RESET_TOKEN_PASSWORD_FAIL";
export const ME_USER_RESET_TOKEN_PASSWORD_REQUEST="ME_USER_RESET_TOKEN_PASSWORD_REQUEST";

export const ALL_USERS_REQUEST = "ALL_USERS_REQUEST";
export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS";
export const ALL_USERS_FAIL = "ALL_USERS_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_RESET = "UPDATE_USER_RESET";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_RESET = "DELETE_USER_RESET";

export const ALL_ERROR_CLEAR="ALL_ERROR_CLEA";